### ISSUE TITLE
Register time execution each function and file

### ISSUE THREAD

**Issue by okitupadmin** [cyrus-and/fracker#4]
Hi,
I was using phptrace module for debugging php applications, but I have certains problems with it.
Now I discover your module and is working fine for me on cgi and fpm.

But I miss to know the time that spends each function and file like phptrace does.
Is it possible to add it in further updates?

Here I attach you a comparassion of same code execution in both modules.
Thanks in advance.

![trace_phptrace](https://user-images.githubusercontent.com/51697420/65143921-68914f80-da16-11e9-909a-200e4d39add5.png)
![trace_fracker](https://user-images.githubusercontent.com/51697420/65143922-6929e600-da16-11e9-963a-565719d823c1.png)

**Comment by cyrus-and** [comment]
That should be easily doable, let me look into that...

**Comment by cyrus-and** [comment]
Actually not so easy because that would require to keep a mapping id -> timestamp for pending functions, either on the C side or the JavaScript side and that's something I want to avoid.

Alternatively, I should be able to fetch this information directly from Xdebug, but it's not working as expected. I've only tried briefly though, I'll dig deeper into this later.

**Comment by cyrus-and** [comment]
Alright, I added the `-m, --show-elapsed-time` option. Example:

```console
$ fracker -m
+++ │ Listening on 0.0.0.0:6666
+++ │
001 │ GET localhost/?x=Hello+Fracker!
001 │ {main}() /var/www/html/index.php +0
001 │ »  explode(" ", "Hello Fracker!") /var/www/html/index.php +11
001 │ »  ~ 120.163us
001 │ »  var_dump(["Hello", "Fracker!"]) /var/www/html/index.php +12
001 │ »  ~ 120.163us
001 │ »  require("/var/www/html/include.php") /var/www/html/index.php +14
001 │ »  »  sleep(3) /var/www/html/include.php +3
001 │ »  »  ~ 3.000s
001 │ »  ~ 3.001s
001 │ »  foo(cmd="Hello") /var/www/html/index.php +15
001 │ »  »  preg_replace("/[^a-z]/i", "", "Hello") /var/www/html/index.php +4
001 │ »  »  ~ 138.044us
001 │ »  »  system("echo Hello") /var/www/html/index.php +4
001 │ »  »  ~ 4.520ms
001 │ »  »  sleep(1) /var/www/html/index.php +5
001 │ »  »  ~ 1.000s
001 │ »  »  nop() /var/www/html/index.php +6
001 │ »  »  ~ 84.877us
001 │ »  ~ 1.006s
001 │ »  require("/var/www/html/include.php") /var/www/html/index.php +14
001 │ »  »  sleep(3) /var/www/html/include.php +3
001 │ »  »  ~ 3.000s
001 │ »  ~ 3.001s
001 │ »  foo(cmd="Fracker!") /var/www/html/index.php +15
001 │ »  »  preg_replace("/[^a-z]/i", "", "Fracker!") /var/www/html/index.php +4
001 │ »  »  ~ 104.904us
001 │ »  »  system("echo Fracker") /var/www/html/index.php +4
001 │ »  »  ~ 3.885ms
001 │ »  »  sleep(1) /var/www/html/index.php +5
001 │ »  »  ~ 1.000s
001 │ »  »  nop() /var/www/html/index.php +6
001 │ »  »  ~ 67.949us
001 │ »  ~ 1.005s
001 │ ~ 8.013s
+++ │
+++ │ Shutting down...
```

**Comment by okitupadmin** [comment]
Wow! I just tried right now, and it's working as expected! Thanks so much! :D
