### ISSUE TITLE
PHP 7.3 Issue with xdebug

### ISSUE THREAD

**Issue by pmfederico** [cyrus-and/fracker#5]
Xdebug has fixed a bug recently:

Fixed bug #1734: Segfault with DBGp "source" with a out-of-range start line number

And this is what I'm getting in my computer:

[ 5633.102448] php-fpm[17184]: segfault at 31 ip 00007fe72f9eb815 sp 00007ffc8091ce30 error 4 in xdebug.so[7fe72f9b8000+44000]

Perhaps it's something you should consider fixing.

Thanks

**Comment by cyrus-and** [comment]
Thanks for the heads up, updating to Xdebug version  2.9.1 was trickier than expected but it should work now.

But unfortunately I'm unable to compile and use Xdebug (even vanilla) with PHP 7.0.33-0+deb9u6, I get:

    /xdebug-2.9.1/src/coverage/code_coverage.c:1001:37: error: 'ZEND_SEND_VAR_NO_REF_EX' undeclared (first use in this function)

Does the same happen to you by any chance?

**Comment by pmfederico** [comment]
@cyrus-and Nope, you should try to talk to derick he is a very accessible and friendly guy, you can find him on irc.freenode.net lurking there, he goes by the nickname of "derick". He is the developer behind Xdebug.

Also his personal website https://derickrethans.nl/

His email: derick@derickrethans.nl

The bug described above happens to me with php 7.3.0, if I can help you with anything else let me know.

Maybe if you talk to him you can convince him to add your features to Xdebug? They are indeed very helpful.

Cheers!

**Comment by cyrus-and** [comment]
So apparently there's a bug in 2.9.1 where the `*_deinit` function of tracers is not called, issue [here][1]. I guess I have to postpone this until this is fixed.

> Maybe if you talk to him you can convince him to add your features to Xdebug?

That'd be nice but I seriously doubt it would happen.

[1]: https://bugs.xdebug.org/view.php?id=1739

**Comment by pmfederico** [comment]
@cyrus-and You don't lose anything in asking, trust me, he is a nice person.

**Comment by cyrus-and** [comment]
Alright, now it uses Xdebug 2.9.2 which includes your fix.
